### ISSUE TITLE
batch changes?

### ISSUE THREAD

**Issue by srevenant** [secretworry/as_nested_set#4]
Can I have it wait to calculate the nested set, so I can do a set of inserts/moves, and then tell it to calculate afterward?

**Comment by secretworry** [comment]
You mean fixing numbers afterward? If you have broken all the `left`, `right` by mistake, or you need to change a tree into a nested set, you have to traverse the whole tree to fix them.

API to fix was on the plan, so I added the traversable interfaces to support this feature(, but I'm not actively updating this project for now).

If you want to do it yourself, you can use the traverse interface to start a deep-first traverse, use `context` to track the current number, and assign `left`, `right` in `prev` and  `post` callback respectively.

**Comment by secretworry** [comment]
To support fully delayed updates, we have to introduce a dirty mark on each node, and then we can find the smallest dirty node and fix numbers from that node, but we have to do the fixing for each node separately, (instead of completing the update in 1-2 update queries for each operation). It will be more inefficient for small updates.

**Comment by srevenant** [comment]
we have a variety of tree's, some of them have upwards of 3.4 million rows; and we receive data from partners in an event driven manner.  When I get time, I'll dig into the code deeper and see if I can find ways to optimize the change.  Right now, running it on a table with 3.4 million nodes is taking ~3-5 minutes, with no optimization on the db, mariadb, and on my local laptop :)
Thanks for your responses, greatly appreciated, very useful!

**Comment by secretworry** [comment]
@srevenant Frequent and noncontinuous updates are not suitable for the nested set since any modification over the structure will lead to almost half of the records get updated( in your case 1.2 million records every time). If possible, a leveled tree( tree of trees) will be a better solution, since the updating will be limited to a smaller range.
