### ISSUE TITLE
@parent_id_column not mapping (NULL values in DB)

### ISSUE THREAD

**Issue by srevenant** [secretworry/as_nested_set#5]
I may be mis-understanding what is used for this attribute.  I am setting it to a different column name (upline_id, instead of the default parent_id).  But this attribute is never set (in the DB it's always NULL).

I was interpreting things such that the id for the target sent into .create() would be included on the child's row as the parent_id.  I see in the code where @parent_id_column is referenced, I'm just not certain why all my values end up being NULL/nil.

Any help is greatly appreciated.  Thanks!

**Comment by secretworry** [comment]
You can find an example in this [testcase](https://github.com/secretworry/as_nested_set/blob/master/test/as_nested_set/modifiable_test.exs#L82)

Basically, if you use `create(new_model, target, :child)`, the framework will assign parent_id to the `new_model` from the `target` automatically for you. So my guess is that, you doen't use the correct `position`. Could you post your code of creating the new node, so we can find out the reason?

All the nested set required fields(`parent_id`, `left`, `right`) should be managed by the framework so that the user would not break their relationship mistakenly.

**Comment by srevenant** [comment]
It must have been a nuance of how I was making the calls in my earlier iteration code, because as I improved my code and expanded to use sample data, the problem resolved itself.  Unfortunately, I cannot provide an easy explanation, than perhaps the map I was sending in as target was not constructed properly.  Thanks!
