### ISSUE TITLE
Transactions in do_safe_create

### ISSUE THREAD

**Issue by slapers** [secretworry/as_nested_set#9]
Hi,

First of all nice work on building this library, the api you expose to consumers looks awesome !
I had a look at the `do_safe_create` in `AsNestedSet.Modifiable` and i was wondering why the 3 database operations are not in a transaction ?
If one of the operations fails would that not cause issues with data consistency of the tree ?

best,
Stefan

**Comment by secretworry** [comment]
@slapers Hi, thx for considering using this lib:)

We introduced the `@type executable` in version 3.x.x ( a delayed execution) as the return value of all APIs, so that it's up to the user to wrap the execution in a transaction or not, how granular the transaction would be. A short sample code would be like this:
```elixir
exec = node |> AsNestedSet.move(:root)
Repo.transaction fn -> AsNestedSet.execute(exec, Repo) end

# or a more coarse but safer version
Repo.transaction fn -> 
  node = loadNode()
  node |> AsNestedSet.move(:root) |> AsNestedSet.execute(exec, Repo)
end
```
I will clarify this in the README later:)

**Comment by slapers** [comment]
@secretworry, super. Thanks for the fast response !!
